services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8010:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: always
