services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./cotizaciones.db:/app/cotizaciones.db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
      - "5173:80"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: always
